### PR TITLE
Add function about show improvement consumption

### PR DESCRIPTION
**Pull request by UncleYi2016**
Add the function about show screw consumption and equipment consumption.

### CODE REVIEW

**Comment by yukixz** [comment]
1. Code style
   Please use 2 spaces indent anywhere.
2. package.json
   hmm... You'd better avoid adding your `package.json` to commit.
3. Could you provide a screenshot?

**Comment by UncleYi2016** [comment]
Well, I have fixed the code style and remove packge.json, but I cannot upload the screenshot through github.  May I provide the screenshot to you through other ways like qq or email?

**Comment by yukixz** [comment]
Nevermind, screenshot is optional.

**Comment by UncleYi2016** [comment]
OK. I got it.

**Pull request closed without merging**
